const { ethers } = window;
const CONFIG = {
  bot: { name:'BOT Chain', network:'BOT testnet', domain:968, chainId:'0x3c8', rpc:'https://rpc.bohr.life', explorer:'https://scan.bohr.life/tx/', icon:'B', kind:'bot', token:'0x75edC9335175Fc0552D51D48439F229c10420fe3', router:'0xb2BFd514997773eBe9AF77E83e153e3A5405CEB6' },
  arb: { name:'Arbitrum', network:'Sepolia testnet', domain:421614, chainId:'0x66eee', rpc:'https://sepolia-rollup.arbitrum.io/rpc', explorer:'https://sepolia.arbiscan.io/tx/', icon:'A', kind:'arb', token:'0x291a962DE3f64fA46f7151c6B7492C04CFDCE5f6', router:'0x291a962DE3f64fA46f7151c6B7492C04CFDCE5f6' }
};
const ERC20 = ['function approve(address,uint256) returns(bool)','function balanceOf(address) view returns(uint256)'];
const ROUTER_ABI = ['function transferRemote(uint32,bytes32,uint256)'];
const readProviders = { bot:new ethers.JsonRpcProvider(CONFIG.bot.rpc,{chainId:968,name:'bot'},{staticNetwork:true}), arb:new ethers.JsonRpcProvider(CONFIG.arb.rpc,{chainId:421614,name:'arbitrum-sepolia'},{staticNetwork:true}) };
let provider, signer, account, reverse = false;
const WALLET_STORAGE_KEY = 'relayline_wallet_connected';
const $ = (id) => document.getElementById(id);
const button=$('connect'), notice=$('notice'), balance=$('balance'), destinationBalance=$('destination-balance'), statusBox=$('transfer-status');
const activityList=$('activity-list');
function route(){ return reverse ? {source:CONFIG.arb,destination:CONFIG.bot} : {source:CONFIG.bot,destination:CONFIG.arb}; }
function say(text,error=false){ notice.textContent=text; notice.style.color=error?'#f09bad':'#968e89'; }
function setSteps(active=-1, done=false){ const names=['Wallet confirmed','Source transaction confirmed','Relayer detected message','Destination delivered']; statusBox.hidden=false; statusBox.innerHTML=names.map((n,i)=>`<div class="status-step ${i<active||done?'done':''} ${i===active&&!done?'active':''}"><span>${i<active||done?'✓':i+1}</span>${n}</div>`).join(''); }
function setRouteLabels(){ const r=route(); const fields=[['from-icon',r.source.icon],['from-name',r.source.name],['from-domain',r.source.domain],['from-network',r.source.network],['to-icon',r.destination.icon],['to-name',r.destination.name],['to-domain',r.destination.domain],['to-network',r.destination.network]]; fields.forEach(([id,v])=>$(id).textContent=v); $('from-icon').className=`chain-icon ${r.source.kind}`; $('to-icon').className=`chain-icon ${r.destination.kind}`; $('amount-symbol').textContent=reverse?'botUSDT':'USDT'; $('source-balance-label').textContent=`${r.source.name} wallet balance`; $('destination-balance-label').textContent=`${r.destination.name} ${reverse?'USDT':'botUSDT'}`; }
async function ensureChain(chain){
  const current=(await window.ethereum.request({method:'eth_chainId'})).toLowerCase();
  if(current===chain.chainId) return;
  try {
    await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:chain.chainId}]});
  } catch(e) {
    const unknown=e.code===4902||e.code===-32602||e.code===-32603||/unrecognized|unknown chain|not added/i.test(e.message||'');
    if(!unknown) throw e;
    await window.ethereum.request({method:'wallet_addEthereumChain',params:[{
      chainId:chain.chainId, chainName:chain.name+' '+chain.network,
      nativeCurrency:{name:chain.kind==='bot'?'tBOT':'ETH',symbol:chain.kind==='bot'?'tBOT':'ETH',decimals:18},
      rpcUrls:[chain.rpc], blockExplorerUrls:[chain.explorer]
    }]});
    const after=(await window.ethereum.request({method:'eth_chainId'})).toLowerCase();
    if(after!==chain.chainId) await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:chain.chainId}]});
  }
}
async function updateBalances(){ if(!account) return; const r=route(); const sourceToken=new ethers.Contract(r.source.token,ERC20,provider); const destToken=new ethers.Contract(r.destination.token,ERC20,readProviders[r.destination.kind]); const [a,b]=await Promise.all([sourceToken.balanceOf(account),destToken.balanceOf(account)]); balance.textContent=`${ethers.formatUnits(a,6)} ${reverse?'botUSDT':'USDT'}`; destinationBalance.textContent=`${ethers.formatUnits(b,6)} ${reverse?'USDT':'botUSDT'}`; return {source:a,destination:b}; }
async function connect(){ if(!window.ethereum){say('No EVM wallet detected. Open this page in MetaMask or Rabby.',true);return;} try{const r=route(); say(`Connect your wallet on ${r.source.name}…`); await ensureChain(r.source); provider=new ethers.BrowserProvider(window.ethereum); signer=await provider.getSigner(); account=await signer.getAddress(); localStorage.setItem(WALLET_STORAGE_KEY,'1'); await updateBalances(); button.innerHTML=`Bridge ${account.slice(0,6)}…${account.slice(-4)} <span>↗</span>`; button.onclick=bridge; say(`Connected on ${r.source.name}. You can start a testnet transfer.`);}catch(e){say(e.shortMessage||e.message||'Wallet connection cancelled.',true);} }
async function restoreWallet(){ if(!window.ethereum||localStorage.getItem(WALLET_STORAGE_KEY)!=='1') return; try{const accounts=await window.ethereum.request({method:'eth_accounts'}); if(!accounts.length)return; provider=new ethers.BrowserProvider(window.ethereum); account=accounts[0]; signer=await provider.getSigner(); const chain=(await window.ethereum.request({method:'eth_chainId'})).toLowerCase(); if(chain===route().source.chainId){await updateBalances();button.innerHTML=`Bridge ${account.slice(0,6)}…${account.slice(-4)} <span>↗</span>`;button.onclick=bridge;say(`Wallet reconnected on ${route().source.name}.`);}else say(`Wallet connected. Switch to ${route().source.name} to continue.`);}catch(_){localStorage.removeItem(WALLET_STORAGE_KEY);} }
async function waitForDestination(before,amount,r){ for(let i=0;i<24;i++){ await new Promise(x=>setTimeout(x,5000)); const c=new ethers.Contract(r.destination.token,['function balanceOf(address) view returns(uint256)'],readProviders[r.destination.kind]); const now=await c.balanceOf(account); if(now>=before+amount) return true; } return false; }
async function bridge(){ try{const r=route(); const text=$('amount').value; if(!text||Number(text)<=0)throw Error('Enter a valid amount.'); const amount=ethers.parseUnits(text,6); const before=await updateBalances(); if(before.source<amount)throw Error('Insufficient balance on the source chain.'); setSteps(0); button.disabled=true; const sourceToken=new ethers.Contract(r.source.token,ERC20,signer); const sourceRouter=new ethers.Contract(r.source.router,ROUTER_ABI,signer); if(!reverse){say('Confirm the USDT approval in your wallet…'); const approval=await sourceToken.approve(r.source.router,amount); await approval.wait();} say('Confirm the bridge transaction in your wallet…'); button.textContent='Confirm transfer…'; const tx=await sourceRouter.transferRemote(r.destination.domain,ethers.zeroPadValue(account,32),amount); setSteps(1); say(`Source submitted: ${tx.hash.slice(0,10)}…`); await tx.wait(); setSteps(2); say('Source confirmed. Automatic relayer is watching the message…'); const delivered=await waitForDestination(before.destination,amount,r); if(!delivered)throw Error('Source succeeded, but destination is still pending. Refresh activity and balance shortly.'); setSteps(3,true); say(`Delivered on ${r.destination.name}. Your ${reverse?'USDT':'botUSDT'} balance has updated.`); await updateBalances(); setTimeout(refresh,1000);}catch(e){say(e.shortMessage||e.message||'Transfer failed.',true);}finally{button.disabled=false;button.innerHTML=`Bridge ${account?account.slice(0,6)+'…'+account.slice(-4):'wallet'} <span>↗</span>`;} }
function render(data){const rows=(data.recent||[]).map(x=>`<div class="activity-item"><span class="chain-icon ${x.direction.includes('BOT')?'bot':'arb'}">↗</span><span class="route">${x.direction}</span><span class="status">Delivered</span><span class="time">${x.time||'recent'}</span>${x.relayTx?`<a class="tx" target="_blank" rel="noreferrer" href="${x.explorer}">tx ↗</a>`:''}</div>`).join('');activityList.innerHTML=rows||'<div class="activity-item"><span class="route">No new transfers yet</span><span class="time">Relayer is watching</span></div>';}
async function refresh(){activityList.innerHTML='<div class="skeleton"></div><div class="skeleton short"></div>';try{const r=await fetch('/api/status',{cache:'no-store'});render(await r.json());}catch(e){activityList.innerHTML='<div class="activity-item"><span class="route">Status unavailable</span><span class="time">Refresh to retry</span></div>';}}
$('flip-route').addEventListener('click',async()=>{reverse=!reverse;setRouteLabels();statusBox.hidden=true;button.onclick=account?bridge:connect;if(account){try{await ensureChain(route().source);provider=new ethers.BrowserProvider(window.ethereum);signer=await provider.getSigner();await updateBalances();say(`Route reversed. Wallet is ready on ${route().source.name}.`);}catch(e){say(e.shortMessage||e.message,true);}}else say(`Connect your wallet on ${route().source.name} testnet.`);});
button.addEventListener('click',connect);$('refresh').addEventListener('click',refresh);setRouteLabels();refresh();restoreWallet();
if(window.ethereum){window.ethereum.on('accountsChanged',async(xs)=>{if(xs[0]){account=xs[0];localStorage.setItem(WALLET_STORAGE_KEY,'1');if(provider)await updateBalances();}else{account=null;signer=null;localStorage.removeItem(WALLET_STORAGE_KEY);button.innerHTML='Connect wallet <span>↗</span>';button.onclick=connect;balance.textContent='Connect wallet';destinationBalance.textContent='—';say('Wallet disconnected.');}});window.ethereum.on('chainChanged',()=>{if(account){provider=new ethers.BrowserProvider(window.ethereum);signer=null;say(`Network changed. Select ${route().source.name} when you are ready.`);}});}
